language: php

services:
    - redis-server
    - elasticsearch
    - rabbitmq

php:
    - 7.1
    - hhvm

sudo: false

matrix:
    allow_failures:
        - php: hhvm

before_script:
    - apt-get install libzmq3-dev
    - echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    - echo "extension = zmq.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    - travis_retry composer self-update
    - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source

script:
    - mkdir -p build/logs
    - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
    - if [[ $TRAVIS_PHP_VERSION != 'hhvm' && $TRAVIS_PHP_VERSION != '7.0' ]]; then php vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover; fi

